name: flask app deployment

# Run this workflow whenever a git push is being prompted
on: push

jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        # Specify some input for this particular action
        with:
          python-version: '3.9.5'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest

      

  deploy:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Deploy App
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.SSHKEY }}
          username: ${{ secrets.USERNAME }}
          script: |
            pip install gunicorn flask
            cd /home/farm
            git pull
            systemctl restart farm